### ISSUE TITLE
New Governance based on Openzeppelin

### ISSUE THREAD

**Issue by Edoumou** [Debond-Protocol/Debond-Governance#6]
# Description

Create the governance contract with all its dependancies. The contract should allow the creation of proposals, voting for proposals, etc. It should also define all parameters needed for the Governance, like the team allocation, how much DBIT should be distributed as rewards to voters, etc.

# Changes to implement

Here are changes that need to be implemented

## Contracts
- [x] Governance: This is the main contract for the governance
- [x] GovStorage: This contract should hold the storage of the governance contract
- [x] StakingDGOV: This contract contains the logic for staking and unstaking DGOV tokens
- [x] Proposal: This contract contains instructions that should be executed by the governance when a proposal passes
- [x] VoteCounting: This contract allows to update the user's vote info. after they voted

# Tests

- [x] Remix tests:
- [x] JS mocha chai tests

**Comment by drikssy** [comment]
[https://app.zenhub.com/files/492777285/399d94a6-f550-43dd-a3af-0210941d928a/download](https://app.zenhub.com/files/492777285/399d94a6-f550-43dd-a3af-0210941d928a/download)

**Comment by Edoumou** [comment]
New logic not based on **Openzeppelin** should be developed according to @yuliu-debond. A contract should be deployed for each proposal. The deployment should be done in the front-end side through a JS script (web3, hardhat, etc.). Solidity side: we need to provide the interface of callback functions that will be fired in case the proposal passes.

@drikssy @dr-chain @GrandGarcon @toufic0710

**Comment by GrandGarcon** [comment]
ok , so in current implementation from my side (interface is defined [here](https://github.com/Debond-Protocol/Debond-Governance/blob/add-Proposal/contracts/interfaces/IProposalFactory.sol)). , so out of all these functions , the proposal will use any of the functions defined in the proposalFacotry and will be executed by anyone if its passed.
